version: "2"
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/fancybull/nginx:1.16.1-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
        - html:/usr/share/nginx/html
        - nginx.conf:/etc/nginx/nginx.conf
        - fastcgi.conf:/etc/nginx/fastcgi.conf
        - log:/var/log/nginx
        - ssl:/opt/ssl
    networks:
      - default

networks:
  default:
    external:
      name: dockernet
