version: "3.2"
services:
  rabbitmq:
    image: registry.cn-hangzhou.aliyuncs.com/fancybull/rabbitmq:3.8
    container_name: rabbitmq
    restart: always
    ports:
      # - "127.0.0.1:61616:61616"
      - "15672:15672"
    volumes:
      # - ./conf:/opt/activemq/conf
      - type: volume
        source: activemq_data
        target: /var/lib/rabbitmq
    network_mode: host
    # networks:
      # - default

# networks:
#   default:
#     external:
#       name: dockernet
volumes:
  activemq_data: