FROM mysql/mysql-server:5.7

RUN set -x && \
    yum install -y \
    tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
    yum clean all 