version: "3.2"
services:
  activemq:
    image: registry.cn-hangzhou.aliyuncs.com/fancybull/activemq:5.15.11 
    container_name: activemq
    restart: always
    # ports:
    #   - "127.0.0.1:61616:61616"
    #   - "8161:8161"
    volumes:
      # - ./conf:/opt/activemq/conf
      - type: volume
        source: activemq_data
        target: /opt/activemq/data
    network_mode: host
    # networks:
      # - default

# networks:
#   default:
#     external:
#       name: dockernet
volumes:
  activemq_data: