version: "2"
services:
  tomcat:
    image: registry.cn-hangzhou.aliyuncs.com/fancybull/tomcat:9.0.31_server-jre-8u241-alpine
    container_name: tomcat
    restart: always
    volumes:
      - ./webapps:/opt/tomcat/webapps
      - ./logs:/opt/tomcat/logs
    networks:
      - hjf

networks:
  hjf:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.238.0/24
